CREATE TABLE person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        username varchar(30) UNIQUE NOT NULL,
                        first_name varchar(20) NOT NULL,
                        last_name varchar(20) NOT NULL,
                        password varchar NOT NULL,
                        email varchar NOT NULL UNIQUE,
                        role varchar
);

CREATE TABLE product (
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         name varchar NOT NULL,
                         description text NOT NULL,
                         count_left int CHECK ( count_left > -1 ),
                         price decimal NOT NULL CHECK ( price > -1 ) DEFAULT 0,
                         photo bytea
);

CREATE TABLE orders (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        status varchar NOT NULL,
                        created_at timestamp WITHOUT TIME ZONE DEFAULT current_timestamp,
                        shipping_address varchar NOT NULL,
                        person_id int REFERENCES person(id)
);

CREATE TABLE cart_item (
                           id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                           username varchar REFERENCES person(username) NOT NULL,
                           product_id int REFERENCES product(id) NOT NULL,
                           quantity int CHECK ( quantity > 0 ) NOT NULL,
                           order_id int REFERENCES orders(id) ON DELETE CASCADE
);